## Fast Fourier Transform

### Introduction

The Discrete Fourier Transform is a mathematical operation that breaks down a function into its constituent frequencies. It is a powerful tool for analyzing signals and understanding the frequency content of a signal. It can be used to analyze periodic signals, as well as non-periodic signals such as those found in audio and image processing. It has many applications in quantum computing, including the design and analysis of quantum algorithms and the simulation of quantum systems.

The Fast Fourier Transform is a more efficient, faster algorithm for calculating the Discrete Fourier Transform. It significantly reduces the computational complexity. 





### Fast Fourier Transform
The following code imports the NumPy and SciPy libraries and uses them to compute the fast Fourier transform.
Create a numpy array x to be used as the input signal.The fft.fft() function computes the Fast Fourier Transform of the input array x and returns the result as a NumPy array y.

The output NumPy array y is a list of complex numbers that encodes the strength of each frequency component in the input signal.
The input to the fft.fft() function is a sequence of numbers that represents a discrete, periodic signal. 

The output array is a sequence of complex numbers, with each number for each frequency component in the signal. The real part of each number encodes the strength of the corresponding frequency component in the signal, and the imaginary part encodes the phase shift of the component.


In [7]:
# Numerical arrays.
import numpy as np

# Fast Fourier transform.
import scipy.fft as fft

In [8]:
# Create a test array.
x = np.array([1.0, 2.0, 1.0, -1.0, 1.5])
x

array([ 1. ,  2. ,  1. , -1. ,  1.5])

In [9]:
# Apply the fast Fourier transform to x.
y = fft.fft(x)
y

array([ 4.5       -0.j        ,  2.08155948-1.65109876j,
       -1.83155948+1.60822041j, -1.83155948-1.60822041j,
        2.08155948+1.65109876j])

### Inverse Fourier Transform
The inverse Fourier transform is an operation that converts a frequency representation of a signal back into its time domain representation. It is the inverse of the Fourier transform. 

In [11]:
# Invert the previous Fourier transform applied to x.
yinv = fft.ifft(y)
yinv

array([ 1. +0.j,  2. +0.j,  1. +0.j, -1. +0.j,  1.5+0.j])