## Fast Fourier Transform

### Introduction

The Discrete Fourier Transform is a mathematical operation that breaks down a function into its constituent frequencies. It is a powerful tool for analyzing signals and understanding the frequency content of a signal. It can be used to analyze periodic signals, as well as non-periodic signals such as those found in audio and image processing. It has many applications in quantum computing, including the design and analysis of quantum algorithms and the simulation of quantum systems.

The Fast Fourier Transform is a more efficient, faster algorithm for calculating the Discrete Fourier Transform. It significantly reduces the computational complexity. 





### Fast Fourier Transform
The following code imports the NumPy and SciPy libraries.They are used them to compute the Fast Fourier Transform.
A numpy array, x, contains the input signal. The input to the fft.fft() function is a sequence of numbers that represents a discrete, periodic signal. The fft.fft() function computes the Fast Fourier Transform of the input array x and returns the result as a Numpy array y. The output numpy array y is a sequence of complex numbers that encodes the strength of each frequency component in the input signal. It has a number for each frequency component in the signal. The real part of each number encodes the strength of the corresponding frequency component in the signal, and the imaginary part encodes the phase shift of the component.


In [1]:
# Numerical arrays.
import numpy as np

# Fast Fourier transform.
import scipy.fft as fft

In [2]:
# Create a test array.
x = np.array([1.0, 2.0, 1.0, -1.0, 1.5])
x

array([ 1. ,  2. ,  1. , -1. ,  1.5])

In [3]:
# Apply the fast Fourier transform to x.
y = fft.fft(x)
y

array([ 4.5       -0.j        ,  2.08155948-1.65109876j,
       -1.83155948+1.60822041j, -1.83155948-1.60822041j,
        2.08155948+1.65109876j])

### Inverse Fourier Transform
The inverse Fourier transform is an operation that converts a frequency representation of a signal back into its time domain representation. It is the inverse of the Fourier transform. The code below takes the output from the Fast Fourier Transform and converts it back into the original signal.

In [4]:
# Invert the previous Fourier transform applied to x.
yinv = fft.ifft(y)
yinv

array([ 1. +0.j,  2. +0.j,  1. +0.j, -1. +0.j,  1.5+0.j])

We expect arrays x and yinv to contain the same values, but they sometimes differ due to numerical errors that can arise when working with floating point numbers. The first element of the arrays x and yinv, 1.0 and (1.0000000000000002+0j) are not exactly equal, but they are very close to each other. You can use the np.isclose() function from the NumPy library that will determine wether the elements of the arrays x and yinv. In this case it says they are.

In [5]:
# Are x and yinv equal?
x == yinv

array([False,  True,  True,  True,  True])

In [6]:
x[0]

1.0

In [7]:
yinv[0]

(1.0000000000000002+0j)

In [8]:
# Adapted from: https://stackoverflow.com/a/39758154
np.isclose(x, yinv)

array([ True,  True,  True,  True,  True])

## The Discrete Fourier Transform Formula

$$y[k] = \sum_{n=0}^{N-1} e^{-2 \pi j \frac{kn}{N}} x[n]$$



The Discrete Fourier Transform is a mathematical operation that decomposes a finite sequence of data points into its constituent frequencies by expressing it as a linear combination of complex exponentials.


To explain the above formula:
* x[n] is the discrete signal in the time domain. N is length of the signal.
* y[k] expresses the signal as a linear combination of complex       exponentials in the frequency domain.
* The symbol ∑ represents a sum, which is a mathematical operation that involves the addition of a sequence of numbers. In this formula, the sum is taken over the range n = 0 to N - 1, which means that the transform considers the contribution of x[n] at all values of n.
* The term $e^{-2 \pi j \frac{kn}{N}}$ is called the complex exponential function, and it plays a central role in the Discrete Fourier Transform. The exponent is a complex number, where j is the imaginary unit and k is the frequency. The function oscillates at a frequency of k and is used to weight the contribution of x[n] at each value of n.
* The term ${-2 \pi}$ is called the argument of the exponent. It determines the angle of rotation of the complex exponential function in the complex plane.



The code below implements the above formula.

The outer loop iterates over the range of k from 0 to N-1, where N is the length of the signal. The inner loop iterates over the range of n from 0 to N-1, which means that the transform considers the contribution of x[n] at all values of n. 

At each iteration of the loop, the code calculates the contribution of x[n] to the frequency k using the formula:

y_k = y_k + (np.e**(-2 * np.pi * 1j * k * n / N) * x[n])




In [11]:
# Calculate by hand.

# Output array.
y = []

N = len(x)

for k in range(N):
    y_k = 0.0
    for n in range(N):
        y_k = y_k + (np.e**(-2 * np.pi * 1j * k * n / N) * x[n])
    y.append(y_k)
    
np.array(y)

array([ 4.5       +0.j        ,  2.08155948-1.65109876j,
       -1.83155948+1.60822041j, -1.83155948-1.60822041j,
        2.08155948+1.65109876j])

Another way of doing this is using scipy library which is a powerful library for scientific and technical computing in Python. 
It provides a wide range of algorithms and tools for working with numerical data. It is widely used in many areas of science and engineering. In regard to signal processing it provides functions for filtering, convolution, and other operations on signals.



This code generates a range of x (input) values for a discrete signal and displays them. It uses the scipy and matplotlib.pyplot libraries.

In [13]:
import scipy

import matplotlib.pyplot as plt
# Number of samples.
N = 600

# Spacing between samples.
T = 1.0 / 800.0

# Range of x (input) values.
x = np.linspace(0.0, N*T, N, endpoint=False)

# Have a look at x.
x

array([0.     , 0.00125, 0.0025 , 0.00375, 0.005  , 0.00625, 0.0075 ,
       0.00875, 0.01   , 0.01125, 0.0125 , 0.01375, 0.015  , 0.01625,
       0.0175 , 0.01875, 0.02   , 0.02125, 0.0225 , 0.02375, 0.025  ,
       0.02625, 0.0275 , 0.02875, 0.03   , 0.03125, 0.0325 , 0.03375,
       0.035  , 0.03625, 0.0375 , 0.03875, 0.04   , 0.04125, 0.0425 ,
       0.04375, 0.045  , 0.04625, 0.0475 , 0.04875, 0.05   , 0.05125,
       0.0525 , 0.05375, 0.055  , 0.05625, 0.0575 , 0.05875, 0.06   ,
       0.06125, 0.0625 , 0.06375, 0.065  , 0.06625, 0.0675 , 0.06875,
       0.07   , 0.07125, 0.0725 , 0.07375, 0.075  , 0.07625, 0.0775 ,
       0.07875, 0.08   , 0.08125, 0.0825 , 0.08375, 0.085  , 0.08625,
       0.0875 , 0.08875, 0.09   , 0.09125, 0.0925 , 0.09375, 0.095  ,
       0.09625, 0.0975 , 0.09875, 0.1    , 0.10125, 0.1025 , 0.10375,
       0.105  , 0.10625, 0.1075 , 0.10875, 0.11   , 0.11125, 0.1125 ,
       0.11375, 0.115  , 0.11625, 0.1175 , 0.11875, 0.12   , 0.12125,
       0.1225 , 0.12

## References 
Fourier transforms (scipy.fft)# (no date) Fourier Transforms (scipy.fft) - SciPy v1.9.3 Manual. Available at: https://docs.scipy.org/doc/scipy/tutorial/fft.html#d-discrete-fourier-transforms (Accessed: December 25, 2022). 

But what is the Fourier Transform? A visual introduction. (2018) YouTube. YouTube. Available at: https://www.youtube.com/watch?v=spUNpyF58BY&amp;t=900s (Accessed: December 25, 2022).

An interactive guide to the Fourier transform (no date) BetterExplained. Available at: https://betterexplained.com/articles/an-interactive-guide-to-the-fourier-transform/ (Accessed: December 25, 2022). 